version: '3.4'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql

  app:
    image: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
    volumes:
      - ./:/home/app

volumes:
  db-config:
  db-data: